name: Project Change
description: Any major or minor change to the project
title: "[CHANGE] "
labels: Planning
assignees: ALCHElVlY

body:
  - type: textarea
    attributes:
      label: Problem description
      description: "Describe the problem in detail"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution description
      description: "Describe what the solution is"
    validations:
      required: true
